SonarSource/sonarqube-mcp-server

- gradle.properties
[MCP-45](https://sonarsource.atlassian.net/browse/MCP-45)
[MCP-45]: https://sonarsource.atlassian.net/browse/MCP-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-45 Prepare next dev iteration

- README.md
- src/main/java/org/sonarsource/sonarqube/mcp/tools/qualitygates/ProjectStatusTool.java
- src/test/java/org/sonarsource/sonarqube/mcp/tools/McpSchemaValidationTest.java
[MCP-47](https://sonarsource.atlassian.net/browse/MCP-47)
[MCP-47]: https://sonarsource.atlassian.net/browse/MCP-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-47 Shorten tool and example server names

- src/main/java/org/sonarsource/sonarqube/mcp/SonarQubeMcpServer.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/ServerApi.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/qualityprofiles/QualityProfilesApi.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/qualityprofiles/package-info.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/qualityprofiles/response/SearchResponse.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/qualityprofiles/response/package-info.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/rules/RulesApi.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/rules/response/SearchResponse.java
- src/main/java/org/sonarsource/sonarqube/mcp/slcore/BackendService.java
- src/main/java/org/sonarsource/sonarqube/mcp/tools/analysis/AnalysisTool.java
- src/test/java/org/sonarsource/sonarqube/mcp/tools/analysis/AnalysisToolTests.java
[MCP-53](https://sonarsource.atlassian.net/browse/MCP-53)
[MCP-53]: https://sonarsource.atlassian.net/browse/MCP-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-53 Apply the server's quality profile when analyzing code

- README.md
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/issues/IssuesApi.java
- src/main/java/org/sonarsource/sonarqube/mcp/tools/issues/SearchIssuesTool.java
- src/test/java/org/sonarsource/sonarqube/mcp/tools/issues/SearchIssuesToolTests.java
[MCP-56](https://sonarsource.atlassian.net/browse/MCP-56)
[MCP-56]: https://sonarsource.atlassian.net/browse/MCP-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-56 Support pagination when fetching issues from a project

- gradle/wrapper/gradle-wrapper.properties
[MCP-58](https://sonarsource.atlassian.net/browse/MCP-58)
[MCP-58]: https://sonarsource.atlassian.net/browse/MCP-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-58 Upgrade the Gradle version

- gradle/libs.versions.toml
- src/main/java/org/sonarsource/sonarqube/mcp/slcore/McpSonarLintRpcClient.java
[MCP-60](https://sonarsource.atlassian.net/browse/MCP-60)
[MCP-60]: https://sonarsource.atlassian.net/browse/MCP-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-60 Use SLCORE 10.24

- gradle.properties
[MCP-61](https://sonarsource.atlassian.net/browse/MCP-61)
[MCP-61]: https://sonarsource.atlassian.net/browse/MCP-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-61 Prepare next dev iteration

- Dockerfile
- README.md
- build.gradle.kts
[MCP-66](https://sonarsource.atlassian.net/browse/MCP-66)
[MCP-66]: https://sonarsource.atlassian.net/browse/MCP-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-66 Consume GitHub artifact from Dockerfile

- README.md
[MCP-66](https://sonarsource.atlassian.net/browse/MCP-66)
[MCP-66]: https://sonarsource.atlassian.net/browse/MCP-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-66 Fix link

- src/main/java/org/sonarsource/sonarqube/mcp/configuration/McpServerLaunchConfiguration.java
- src/test/java/org/sonarsource/sonarqube/mcp/configuration/McpServerLaunchConfigurationTest.java
[MCP-65](https://sonarsource.atlassian.net/browse/MCP-65)
[MCP-65]: https://sonarsource.atlassian.net/browse/MCP-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-65 Support empty env vars and system properties

- Dockerfile
[MCP-72](https://sonarsource.atlassian.net/browse/MCP-72)
* Please review our [contribution guidelines](https://github.com/SonarSource/sonarqube-mcp-server/blob/master/docs/contributing.md).
And please ensure your pull request adheres to the following guidelines: 
[MCP-72]: https://sonarsource.atlassian.net/browse/MCP-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-72 Fix Docker SSLProtocolException

- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/qualitygates/response/ListResponse.java
- src/main/java/org/sonarsource/sonarqube/mcp/tools/qualitygates/ListQualityGatesTool.java
- src/main/java/org/sonarsource/sonarqube/mcp/tools/rules/ShowRuleTool.java
- src/test/java/org/sonarsource/sonarqube/mcp/tools/qualitygates/ListQualityGatesToolTests.java
- src/test/java/org/sonarsource/sonarqube/mcp/tools/rules/ShowRuleToolTests.java
[MCP-67](https://sonarsource.atlassian.net/browse/MCP-67)
[MCP-69](https://sonarsource.atlassian.net/browse/MCP-69)
`show_rule`:
`list_quality_gates`:
[MCP-67]: https://sonarsource.atlassian.net/browse/MCP-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MCP-69]: https://sonarsource.atlassian.net/browse/MCP-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-67 MCP-69 Fix show_rule and list_quality_gates

- Dockerfile
- gradle.properties
- gradle/libs.versions.toml
[MCP-80](https://sonarsource.atlassian.net/browse/MCP-80)
[MCP-80]: https://sonarsource.atlassian.net/browse/MCP-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-80 Update for new development iteration, Dockerfile and SLCORE dependency

- Dockerfile
- README.md
- gradle/libs.versions.toml
- scripts/install-certificates.sh
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/ServerApiHelper.java
[MCP-79](https://sonarsource.atlassian.net/browse/MCP-79)
[MCP-82](https://sonarsource.atlassian.net/browse/MCP-82)
[MCP-70](https://sonarsource.atlassian.net/browse/MCP-70)
[MCP-79]: https://sonarsource.atlassian.net/browse/MCP-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MCP-82]: https://sonarsource.atlassian.net/browse/MCP-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MCP-70]: https://sonarsource.atlassian.net/browse/MCP-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-79 MCP-82 MCP-70 Support for certificates, remove deprecated usages, update dependencies

- Dockerfile
- gradle.properties
- gradle/libs.versions.toml
[MCP-91](https://sonarsource.atlassian.net/browse/MCP-91)
[MCP-91]: https://sonarsource.atlassian.net/browse/MCP-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-91 Prepare next development iteration

- .sonarlint/connectedMode.json
- README.md
- build.gradle.kts
[MCP-95](https://sonarsource.atlassian.net/browse/MCP-95)
[MCP-95]: https://sonarsource.atlassian.net/browse/MCP-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-95 Fix new SQ project key

- README.md
- src/main/java/org/sonarsource/sonarqube/mcp/SonarQubeMcpServer.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/ServerApi.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/issues/IssuesApi.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/qualitygates/QualityGatesApi.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/rules/RulesApi.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/webhooks/WebhooksApi.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/webhooks/package-info.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/webhooks/response/CreateResponse.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/webhooks/response/ListResponse.java
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/webhooks/response/package-info.java
- src/main/java/org/sonarsource/sonarqube/mcp/tools/webhooks/CreateWebhookTool.java
- src/main/java/org/sonarsource/sonarqube/mcp/tools/webhooks/ListWebhooksTool.java
- src/main/java/org/sonarsource/sonarqube/mcp/tools/webhooks/package-info.java
- src/test/java/org/sonarsource/sonarqube/mcp/tools/webhooks/CreateWebhookToolTests.java
- src/test/java/org/sonarsource/sonarqube/mcp/tools/webhooks/ListWebhooksToolTests.java
[MCP-93](https://sonarsource.atlassian.net/browse/MCP-93)
[MCP-94](https://sonarsource.atlassian.net/browse/MCP-94)
[MCP-93]: https://sonarsource.atlassian.net/browse/MCP-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MCP-94]: https://sonarsource.atlassian.net/browse/MCP-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-93 MCP-94 Add tools for webhooks

- .cirrus.yml
- .cirrus/run-iris.sh
[MCP-100](https://sonarsource.atlassian.net/browse/MCP-100)
[MCP-100]: https://sonarsource.atlassian.net/browse/MCP-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-100 Mcp 87 Fix and align unifying dogfooding

- .github/workflows/build.yml
[MCP-115](https://sonarsource.atlassian.net/browse/MCP-115)
[MCP-115]: https://sonarsource.atlassian.net/browse/MCP-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-115 Enable Develocity with GitHub Actions

- .github/workflows/release.yml
[MCP-121](https://sonarsource.atlassian.net/browse/MCP-121)
[MCP-121]: https://sonarsource.atlassian.net/browse/MCP-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-121 Use latest GitHub release action

- GEMINI.md
- README.md
- src/main/java/org/sonarsource/sonarqube/mcp/serverapi/issues/IssuesApi.java
- src/main/java/org/sonarsource/sonarqube/mcp/tools/issues/SearchIssuesTool.java
- src/test/java/org/sonarsource/sonarqube/mcp/tools/issues/SearchIssuesToolTests.java
[MCP-136](https://sonarsource.atlassian.net/browse/MCP-136)
[MCP-136]: https://sonarsource.atlassian.net/browse/MCP-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-136 Add ability to filter by severity on search_sonar_issues_in_projects

- README.md
[MCPZ-6](https://sonarsource.atlassian.net/browse/MCPZ-6)
[MCPZ-6]: https://sonarsource.atlassian.net/browse/MCPZ-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCPZ-6 Add configuration for integration with Zed

- Dockerfile
- gemini-extension.json
- gradle.properties
[MCP-146](https://sonarsource.atlassian.net/browse/MCP-146)
[MCP-146]: https://sonarsource.atlassian.net/browse/MCP-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-146 Release 1.0.0

- README.md
[MCP-147](https://sonarsource.atlassian.net/browse/MCP-147)
This change adds relevant links to Terms & Conditions that apply when using the MCP combined with SQC/SQS.
And please ensure your pull request adheres to the following guidelines: 
[MCP-147]: https://sonarsource.atlassian.net/browse/MCP-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-147 Update README.md adding links to relevant T&C

- src/main/java/org/sonarsource/sonarqube/mcp/SonarQubeMcpServer.java
- src/main/java/org/sonarsource/sonarqube/mcp/tools/dependencyrisks/SearchDependencyRisksTool.java
- src/test/java/org/sonarsource/sonarqube/mcp/harness/SonarQubeMcpTestClient.java
- src/test/java/org/sonarsource/sonarqube/mcp/tools/dependencyrisks/SearchDependencyRisksToolTests.java
[MCP-156](https://sonarsource.atlassian.net/browse/MCP-156)
[MCP-156]: https://sonarsource.atlassian.net/browse/MCP-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MCP-156 Stop checking SCA enablement at startup
